spring:
  profile:
    active:
    - dev
---
server:
  port: 8201
spring:
  profile: dev
  application:
    name: microservice-config-client
eureka:
  client:
    service-url:
      dafaultZone: http://eureka-dev.com/7001/eureka/
---
server:
  port: 8202
spring:
  profile: test
  application:
    name: microservice-config-client
eureka:
  client:
    service-url:
      dafaultZone: http://eureka-dev.com/7001/eureka/