spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-test-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: microservicecloud-config-test-test
#一定要保存为UTF-8格式