spring:
  profile:
    active:
    - dev
---
server:
  port: 8001
spring:
  profile: dev
  application:
    name: microservicecloud-config-dept-client                       #当前数据源操作类型
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           #mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone = GMT         #数据库名称
    username: root
    password: 152000
    dbcp2:
      min-idle: 5                                       #数据库连接池的最小维持连接数
      initial-size: 5                                   #初始化连接数
      max-total: 5                                      #最大化连接数
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件所在路径
  type-aliases-package: com.test.springcloud.entities  #所有entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-8001测试           #自定义在eureka微服务列表中的服务名称
    prefer-ip-address: true                       #访问路径可以显示IP

info:
  app.name: zp-microservicecloud-config01
  company.name: www.zp.com
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$

---
server:
  port: 8001
spring:
  profile: test
  application:
    name: microservicecloud-config-dept-client                       #当前数据源操作类型
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           #mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?serverTimezone = GMT         #数据库名称
    username: root
    password: 152000
    dbcp2:
      min-idle: 5                                       #数据库连接池的最小维持连接数
      initial-size: 5                                   #初始化连接数
      max-total: 5                                      #最大化连接数
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件所在路径
  type-aliases-package: com.test.springcloud.entities  #所有entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-8001测试           #自定义在eureka微服务列表中的服务名称
    prefer-ip-address: true                       #访问路径可以显示IP

info:
  app.name: zp-microservicecloud-config02
  company.name: www.zp.com
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$